import 'package:flutter/material.dart';

import 'package:get/get.dart';

import '../../const.dart';
import '../../custom_widgets.dart';
import '../controllers/billing_controller.dart';

class BillingView extends GetView<BillingController> {
  BillingView({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: getPayslip(),
      ),
    );
  }

  double bodySize = Get.width - getSideBarSize();

  getText(text, {width = 0.3}) {
    return Container(
      width: Get.width * width,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(16),
          color: const Color(0xffE9E9E9)),
      child: Text(text),
    );
  }

  getTextRow(text1, text2) {
    return Row(
      children: [getText(text1), horizontalSpaceMedium, getText(text2)],
    );
  }

  getPlaceHolder() {
    return Container(
      decoration: BoxDecoration(
          color: const Color(0xffE9E9E9),
          borderRadius: BorderRadius.circular(30)),
      width: Get.width * 0.15,
      height: 35,
    );
  }

  getAmountSection(topic, fields) {
    getSizedText(text, {width = 0.15, size = 20}) {
      return SizedBox(
          width: Get.width * width,
          child: Text(text,
              style: getDonegalOneStyle(
                  size: size, color: Colors.black.withOpacity(0.6))));
    }

    return Column(
      children: [
        Row(
          children: [
            getSizedText(topic, size: 24),
            getSizedText('Amount', size: 24),
          ],
        ),
        verticalSpaceSmall,
        Column(
          mainAxisAlignment: MainAxisAlignment.start,
          children: List.generate(fields.length, (index) {
            return Padding(
              padding: const EdgeInsets.only(bottom: 12.0),
              child: Row(
                children: [getSizedText(fields[index]), getPlaceHolder()],
              ),
            );
          }),
        ),
      ],
    );
  }

  getBtn(text) {
    return InkWell(
        onTap: () {},
        child: Container(
          padding: const EdgeInsets.all(20),
          decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(30), color: pink),
          child:
              Text(text, style: getPoppinsStyle(size: 24, color: Colors.white)),
        ));
  }

  getPayslip() {
    return Container(
      padding: const EdgeInsets.all(32),
      width: bodySize,
      decoration: BoxDecoration(
        color: Colors.grey.shade100,
      ),
      child: Center(
        child: Container(
          decoration: BoxDecoration(
              color: Colors.white, borderRadius: BorderRadius.circular(10)),
          width: Get.width * 0.75,
          padding: const EdgeInsets.all(32),
          child: SizedBox(
            width: Get.width * 0.5,
            child: SingleChildScrollView(
              child: Column(children: [
                Text('GENERATE BILL',
                    style: getPoppinsStyle(size: 40, color: pink)),
                verticalSpaceRegular,
                getText('MM/DD/YYYY'),
                verticalSpaceRegular,
                getText('Name'),
                verticalSpaceRegular,
                getText('Quantity'),
                verticalSpaceRegular,
                getText('Payment Method'),
                verticalSpaceRegular,
                getText('Amount'),
                verticalSpaceRegular,
                getText('Generated By'),
                verticalSpaceLarge,
                SizedBox(
                  width: Get.width * 0.3,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: [
                      getBtn('PRINT'),
                    ],
                  ),
                )
              ]),
            ),
          ),
        ),
      ),
    );
  }
}
